# Generated by Django 5.0.4 on 2024-04-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
