# Generated by Django 5.0.4 on 2024-04-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_calculator_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculator',
            old_name='value',
            new_name='values',
        ),
    ]
