# Generated by Django 5.0.4 on 2024-04-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_rename_value_calculator_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculator',
            old_name='values',
            new_name='value',
        ),
    ]
